name: Full Maven Compile
on:
  workflow_call:
#on:
#  push:
#    paths:
#      - '.github/workflows/build.yaml'
#      - 'java/**'

jobs:
  check-status:
    uses: ./.github/workflows/check-status.yaml

  full-compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: java/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Resolve dependencies
        run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies -Dmaven.repo.local=.m2/repository
        working-directory: ./java
      - name: Build with Maven
        run: mvn --batch-mode verify -Pquick -Dmaven.repo.local=.m2/repository
        working-directory: ./java
