name: Check chunk status
on:
  push:
#  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: java/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Resolve dependencies
        run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies -Dmaven.repo.local=.m2/repository
        working-directory: ./java
      - name: Query GitHub
        working-directory: ./java/build
        run: |
          echo "token=${{ secrets.GITHUB_TOKEN }}" >> github.properties
          echo "repository=${{ github.repository }}" >> github.properties
          echo "head.branch=${{ github.ref_name }}" >> github.properties
          echo "head.sha=${{ github.sha }}" >> github.properties
          CHUNKS_YAML=${{ github.workspace }}/.github/config/chunks.yaml
          MAVEN_PROJECT=${{ github.workspace }}/java
          mvn compile exec:java -q -e -Dexec.mainClass=sleeper.build.status.CheckGitHubStatusMain \
            -Dmaven.repo.local=../.m2/repository \
            -Dexec.args="github.properties $CHUNKS_YAML $MAVEN_PROJECT"
